"""The small engine contract shared by MuJoCo today and future engines."""

from __future__ import annotations

from typing import Any, Protocol


class ViewerEngine(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def frame(self) -> dict[str, Any]: ...
    def scene_manifest(self) -> dict[str, Any]: ...
    def state(self) -> dict[str, Any]: ...
    def control(self, action: str, value: Any = None) -> None: ...
